services:
  3xui:
    image: ghcr.io/mhsanaei/3x-ui:latest # Use the pre-built image instead of building locally
    container_name: 3xui_app
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
    tty: true
    restart: unless-stopped
    # 1. Map the panel port so you can access it via IP:2053
    # 2. Map your REALITY port (54321) so it's reachable from the outside
    ports:
      - "2053:2053"
      - "54321:54321"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
